work_dir = '/home/xieyong/16S/03-filt/02+aquatic/qiime2/Diversity/core-metrics-results/beta'

# beta-div distance matrices
beta_div_file = '/home/xieyong/16S/03-filt/02+aquatic/qiime2/Diversity/core-metrics-results/beta/beta_div.RDS'

# params
threads = 12

library(dplyr)
library(tidyr)
library(ggplot2)
library(stringr)
library(ape)
library(ecodist)
library(phyloseq)
library(doParallel)

dist_mtx_order = function(d, x){
    # Ordering distance matrixes
    # d = distance matrix (dist class)
    # x = vector to order dist. obj. by
    m = d %>% as.matrix
    d = as.dist(m[x,x])
    return(d)
}
##Metadata
metadata <- read.table("metadata",sep="\t",header=T)
rownames(metadata) <- metadata[,1]
##Beta diversity
rescale_dist_mtx = function(m){
    m = m %>% as.matrix
    labs = m %>% colnames
    n_row = m %>% nrow
    n_col = m %>% ncol
    x = m %>% as.vector 
    x = scales::rescale(x) 
    m = matrix(x, nrow=n_row, ncol=n_col)
    colnames(m) = labs
    rownames(m) = labs
    m = m %>% as.dist
    return(m)
}
# load beta-diversity dist. matrices
beta_d = readRDS(beta_div_file)

# status
lapply(beta_d, function(x) x %>% as.vector %>% summary)
beta_d = lapply(beta_d, dist_mtx_order, metadata$X.SampleID) 

lapply(beta_d, function(x) x %>% as.matrix %>% dim)

##Load

Host_D = metadata %>%   dplyr::select(X.SampleID, P) %>%  as.data.frame
rownames(Host_D) = Host_D$X.SampleID
Host_D$X.SampleID = NULL
Host_D %>% head
Host_d = cluster::daisy(Host_D, metric='gower')


Diet_D = metadata %>%   dplyr::select(X.SampleID, D) %>%  as.data.frame
rownames(Diet_D) = Diet_D$X.SampleID
Diet_D$X.SampleID = NULL
Diet_D %>% head
Diet_d = cluster::daisy(Diet_D, metric='gower')


Captivity_D = metadata %>%   dplyr::select(X.SampleID, C) %>%  as.data.frame
rownames(Captivity_D) = Captivity_D$X.SampleID
Captivity_D$X.SampleID = NULL
Captivity_D %>% head
Captivity_d = cluster::daisy(Captivity_D, metric='gower')

Habitat_D = metadata %>%   dplyr::select(X.SampleID, H) %>%  as.data.frame
rownames(Habitat_D) = Habitat_D$X.SampleID
Habitat_D$X.SampleID = NULL
Habitat_D %>% head
Habitat_d = cluster::daisy(Habitat_D, metric='gower')

Endan_D = metadata %>%   dplyr::select(X.SampleID, E) %>%  as.data.frame
rownames(Endan_D) = Endan_D$X.SampleID
Endan_D$X.SampleID = NULL
Endan_D %>% head
Endan_d = cluster::daisy(Endan_D, metric='gower')

La_D = metadata %>%   dplyr::select(X.SampleID, la) %>%  as.data.frame
rownames(La_D) = La_D$X.SampleID
La_D$X.SampleID = NULL
La_D %>% head
La_d = cluster::daisy(La_D, metric='gower')

Tem_D = metadata %>%   dplyr::select(X.SampleID, tmp) %>%  as.data.frame
rownames(Tem_D) = Tem_D$X.SampleID
Tem_D$X.SampleID = NULL
Tem_D %>% head
Tem_d = cluster::daisy(Tem_D, metric='gower')

##Ordering matrices

beta_d %>% labels

# ordering by beta-div metrix
X = labels(beta_d$weighted_unifrac)
Host_d_o = dist_mtx_order(Host_d, X)
Diet_d_o = dist_mtx_order(Diet_d, X)
Habitat_d_o = dist_mtx_order(Habitat_d, X)
Endan_d_o = dist_mtx_order(Endan_d, X)
Captivity_d_o = dist_mtx_order(Captivity_d, X)
La_d_o = dist_mtx_order(La_d, X)
Tem_d_o = dist_mtx_order(Tem_d, X)

X %>% length %>% print
Diet_d_o %>% labels %>% length %>% print

##MRM intra-spec sensitivity

# number of permutated SpecD datasetst
nperm_datasets = 100
# number of permutations per MRM analysis
nperm = 1000


#' randomly selecting one per group
#' L : list of distance matrixes used for MRM
#' df_grps : data.frame (sample, group)
one_per_group = function(L, df_grps, ...){
    # get subsample
    colnames(df_grps) = c('Sample', 'Group')
    df_grps = df_grps %>%
        group_by(Group) %>%
        sample_n(1)
    # subsetting all matrices
    lapply(L, function(x) dist_mtx_order(x, df_grps$Sample))
}
#' MRM on one subsample rep
#' i : rep number
#' L : list of list of distance matrices generated by `one_per_group()`
# nperm : nperm function for MRM
# f : MRM fomulat
mrm_each = function(i, L, f, nperm=99){
    m = L[[i]]
    f = as.formula(f)
    x = ecodist::MRM(f, nperm=nperm, mrank=TRUE)
    # coefficients
    df = x$coef %>% as.data.frame
    colnames(df) = c('coef', 'coef_pval')
    df$variable = rownames(df)
    df$R2 = x$r.squared[1]
    df$pval = x$r.squared[2]
    df$F = x$F.test[1]
    df$rep = i
    return(df)
}

df_grps = metadata %>% filter(X.SampleID %in% labels(Diet_d_o)) %>%    dplyr::select(X.SampleID, Host)
df_grps %>% head


##Weighted unifrac



L = list(beta = beta_d$weighted_unifrac,Host = Host_d_o,Diet = Diet_d_o,Captivity = Captivity_d_o,Habitat = Habitat_d_o,Endan = Endan_d_o, Tem = Tem_d_o,La = La_d_o)

m_perm = lapply(as.list(1:nperm_datasets), function(x) one_per_group(L, df_grps, x))
x = as.list(1:length(m_perm))
f = 'm$beta ~ m$Host + m$Diet + m$Captivity + m$Habitat + m$Endan + m$Tem + m$La'
mrm_res = plyr::llply(x, mrm_each, L=m_perm, f=f, nperm=nperm)
mrm_res = do.call(rbind, mrm_res)

write.table(mrm_res,"weighted_unifrac-mrm_res.txt",sep = "\t",row.names = F,quote = F)


##bray_curtis

L = list(beta = beta_d$bray_curtis,Host = Host_d_o,Diet = Diet_d_o,Captivity = Captivity_d_o,Habitat = Habitat_d_o,Endan = Endan_d_o, Tem = Tem_d_o,La = La_d_o)

m_perm = lapply(as.list(1:nperm_datasets), function(x) one_per_group(L, df_grps, x))
x = as.list(1:length(m_perm))
f = 'm$beta ~ m$Host + m$Diet + m$Captivity + m$Habitat + m$Endan + m$Tem + m$La'
mrm_res = plyr::llply(x, mrm_each, L=m_perm, f=f, nperm=nperm)
mrm_res = do.call(rbind, mrm_res)

write.table(mrm_res,"bray_curtis-mrm_res.txt",sep = "\t",row.names = F,quote = F)

##jaccard

L = list(beta = beta_d$jaccard,Host = Host_d_o,Diet = Diet_d_o,Captivity = Captivity_d_o,Habitat = Habitat_d_o,Endan = Endan_d_o, Tem = Tem_d_o,La = La_d_o)

m_perm = lapply(as.list(1:nperm_datasets), function(x) one_per_group(L, df_grps, x))
x = as.list(1:length(m_perm))
f = 'm$beta ~ m$Host + m$Diet + m$Captivity + m$Habitat + m$Endan + m$Tem + m$La'
mrm_res = plyr::llply(x, mrm_each, L=m_perm, f=f, nperm=nperm)
mrm_res = do.call(rbind, mrm_res)

write.table(mrm_res,"jaccard-mrm_res.txt",sep = "\t",row.names = F,quote = F)

##unweighted_unifrac



L = list(beta = beta_d$unweighted_unifrac,Host = Host_d_o,Diet = Diet_d_o,Captivity = Captivity_d_o,Habitat = Habitat_d_o,Endan = Endan_d_o, Tem = Tem_d_o,La = La_d_o)

m_perm = lapply(as.list(1:nperm_datasets), function(x) one_per_group(L, df_grps, x))
x = as.list(1:length(m_perm))
f = 'm$beta ~ m$Host + m$Diet + m$Captivity + m$Habitat + m$Endan + m$Tem + m$La'
mrm_res = plyr::llply(x, mrm_each, L=m_perm, f=f, nperm=nperm)
mrm_res = do.call(rbind, mrm_res)

write.table(mrm_res,"unweighted_unifrac-mrm_res.txt",sep = "\t",row.names = F,quote = F)


